name = "terminal-cookbook"
license = "MIT"
licenselink = "https://git.ullmann.space/rullmann/hugo-theme-terminal-cookbook/src/branch/main/LICENSE"
description = "A hugo theme for recipes made for minimalist terminal enthusiasts"
homepage = "https://git.ullmann.space/rullmann/hugo-theme-terminal-cookbook"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Rico Ullmann"
  homepage = "https://ullmann.space"
